using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace _1DV402.S2.L1A
{
    public class SecretNumber
    {

        private int _count;
        private int _number;
        public const int MaxNumberOfGuesses = 7;

        /// <summary>
        /// Constructor
        /// </summary>
        public SecretNumber()
        {
            Initialize();
        }

        /// <summary>
        /// Initializes each new round by setting the _count field to zero and generating a random number between 1-100.
        /// </summary>
        public void Initialize()
        {
            _count = 0;
            Random random = new Random();
            _number = random.Next(1, 101);
        }

        /// <summary>
        /// Matches the guess against the random number generated by Initialize(). Checks that the input guess is a valid number and that the _count field is less than the Maximum allowed no. of guesses.
        /// </summary>
        /// <param name="number">The guess</param>
        /// <returns>If the guess is right or wrong</returns>
        public bool MakeGuess(int number)
        {
            if (number < 1 || number > 100)
            {
                throw new ArgumentOutOfRangeException();
            }
            else if (_count >= MaxNumberOfGuesses)
            {
                throw new ApplicationException();
            }
            else
            {
                bool correct = false;
                if (number != _number)
                {
                    string faultKind = null;
                    if (number < _number)
                    {
                        faultKind = "lågt";
                    }
                    else
                    {
                        faultKind = "högt";
                    }
                    _count++;
                    Console.WriteLine("{0} är för {1}. Du har {2} gissningar kvar.", number, faultKind, MaxNumberOfGuesses - _count);
                    if (_count >= MaxNumberOfGuesses)
                    {
                        Console.WriteLine("\nTyvärr, du lyckades inte gissa rätt på {0} försök. Det hemliga talet är... {1}!!!!!", MaxNumberOfGuesses, _number);
                    }
                }
                else
                {
                    Console.WriteLine("RÄTT GISSAT! Du klarade det på {0} försök.", _count + 1);
                    correct = true;
                }
                return correct; 
            }
        }
    }
}
